// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEy5twKhsgUuyV3yzkh8FTvJoF8uZp8QQ',
    appId: '1:294546873061:web:fca58c7ae1b9bc8ebf120c',
    messagingSenderId: '294546873061',
    projectId: 'voice-sphere-216ae',
    authDomain: 'voice-sphere-216ae.firebaseapp.com',
    storageBucket: 'voice-sphere-216ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHiswZC7Bbk_UlmIEuzjwhaUZIQtSwqSY',
    appId: '1:294546873061:android:72f146119a789876bf120c',
    messagingSenderId: '294546873061',
    projectId: 'voice-sphere-216ae',
    storageBucket: 'voice-sphere-216ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCnhua_1mQBl-xOo3HRcg8rHDkSb-iM8Y',
    appId: '1:294546873061:ios:b3a5631ecea46985bf120c',
    messagingSenderId: '294546873061',
    projectId: 'voice-sphere-216ae',
    storageBucket: 'voice-sphere-216ae.appspot.com',
    iosBundleId: 'com.example.voicesphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCnhua_1mQBl-xOo3HRcg8rHDkSb-iM8Y',
    appId: '1:294546873061:ios:b3a5631ecea46985bf120c',
    messagingSenderId: '294546873061',
    projectId: 'voice-sphere-216ae',
    storageBucket: 'voice-sphere-216ae.appspot.com',
    iosBundleId: 'com.example.voicesphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEy5twKhsgUuyV3yzkh8FTvJoF8uZp8QQ',
    appId: '1:294546873061:web:6a300b2d304adf4dbf120c',
    messagingSenderId: '294546873061',
    projectId: 'voice-sphere-216ae',
    authDomain: 'voice-sphere-216ae.firebaseapp.com',
    storageBucket: 'voice-sphere-216ae.appspot.com',
  );
}
